In [1]:
from genetic_alg import genetic_alg
from problems import *
from individuals import *

In [2]:
def generate_problems(per_class = 2):
    problems = []
    max_total_weights = [10, 20, 30]
    item_counts = [5, 10, 20]
    test_cases = []
    for iteration in range(per_class):
        for total_weight in max_total_weights:
            for count in item_counts:
            
                test_case = {
                    'maximum_total_weight': total_weight,
                    'item_count': count
                }
                test_cases.append(test_case)
                
    for case in test_cases:
        problems.append(knapsack(minimum_item_weight=0,maximum_item_weight=10, **case))
    return problems

In [3]:
problems = generate_problems()
print(len(problems))

18

In [4]:
algs = []
pop_sizes = [6, 10, 20]
crossover_types = ["one point", "uniform", "two point"]
mutation_probabilities = [0.05, 0.1, 0.2]
selection_methods = ["roulette", "tournament"]
roulette_params = [0,0.2,0.5]
tournament_fracs = [0.2,0.4,0.6]
for problem in problems:
    for pop_size in pop_sizes:
        for crossover_type in crossover_types:
            for mutation_probability in mutation_probabilities:
                for selection_method in selection_methods:
                    if selection_method == 'tournament':
                        for tournament_frac in tournament_fracs:
                            for tournament_frac in tournament_fracs:
                                alg = genetic_alg(
                                    pop_size=pop_size,
                                    genome_size=problem.get_item_count(),
                                    crossover_type=crossover_type, 
                                    mutation_method="gene bitflip", 
                                    mutation_probability=mutation_probability,
                                    problem=problem,
                                    genome_type='bitstring',
                                    selection_method=selection_method, 
                                    tournament_frac=tournament_frac,tournament_prob=tournament_frac)
                                algs.append(alg)
                    else:
                        for roulette_param in roulette_params:
                            alg = genetic_alg(
                                    pop_size=pop_size,
                                    genome_size=problem.get_item_count(),
                                    crossover_type=crossover_type, 
                                    mutation_method="gene bitflip", 
                                    mutation_probability=mutation_probability,
                                    problem=problem,
                                    genome_type='bitstring',
                                    selection_method=selection_method, 
                                    roulette_param=roulette_param)
                            algs.append(alg)

In [5]:
from tqdm import tqdm
for alg in tqdm(algs):
    alg.run(50)

100%|██████████| 5832/5832 [42:36<00:00,  2.28it/s]

In [6]:
import pickle
def save_object(obj, filename):
    with open(filename, 'wb') as outp:  # Overwrites any existing file.
        pickle.dump(obj, outp, pickle.HIGHEST_PROTOCOL)

# sample usage
for i, alg in enumerate(algs):
    save_object(algs[i], 'objects1/'+str(i)+'.pkl')

In [7]:
algs[50].run(50)

In [8]:
import pickle

In [13]:
len(algs)

5832

In [12]:
import pandas as pd
data = []
for alg in algs:
    # Extract algorithm parameters and performance metrics
    parameters = {
        'pop_size': alg.pop_size,
        'crossover_type': alg.crossover_type,
        'mutation_probability': alg.mutation_probability,
        'selection_method': alg.selection_method
    }
    history = alg.get_history()
    # Combine parameters and history
    row_data = {**parameters, **history.iloc[history['Best fitness'].idxmax()]}
    
    # Append to the data list
    data.append(row_data)
    
    max_fitness_index = alg.get_history()['Best fitness'].idxmax()
    best_row = history.loc[max_fitness_index]
df = pd.DataFrame(data)

In [ ]:
df

,pop_size,crossover_type,mutation_probability,selection_method,Generation,Best fitness,Mean fitness,Fitness variance,Best genome
0,6,one point,0.05,roulette,1,11,9.166667,6.138889,"[0, 1, 0, 1, 1]"
1,6,one point,0.05,tournament,1,10,5.000000,15.333333,"[1, 0, 0, 1, 1]"
2,6,one point,0.10,roulette,1,3,0.500000,1.250000,"[0, 0, 1, 0, 0]"
3,6,one point,0.10,tournament,1,11,4.166667,17.138889,"[0, 1, 0, 1, 1]"
4,6,one point,0.20,roulette,1,6,6.000000,0.000000,"[1, 0, 0, 0, 1]"
...,...,...,...,...,...,...,...,...,...
967,20,two point,0.05,tournament,1,152,30.150000,2049.527500,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, ..."
968,20,two point,0.10,roulette,4,119,79.200000,458.460000,"[1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, ..."
969,20,two point,0.10,tournament,7,134,16.200000,1563.460000,"[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, ..."
970,20,two point,0.20,roulette,7,108,82.250000,113.887500,"[1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, ..."
971,20,two point,0.20,tournament,3,121,18.750000,1483.787500,"[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, ..."

In [ ]:
alg = genetic_alg(
    pop_size=50,
    genome_size=10,
    crossover_type="one point", 
    mutation_method="gene bitflip", 
    mutation_probability=0.1,
    problem=problem,
    genome_type='bitstring',
    selection_method="roulette")
alg.run(50)

ValueError: Length of values (10) does not match length of index (20)

In [ ]:
alg = genetic_alg(
    pop_size=50,
    genome_size=10,
    crossover_type="one point", 
    mutation_method="gene bitflip", 
    mutation_probability=0.1,
    problem=problem,
    genome_type='bitstring',
    selection_method="tournament")
alg.run(50)

In [ ]:
alg.get_history()

,Generation,Best fitness,Mean fitness,Fitness variance,Best genome
0,1,41,20.80,119.6000,"[0, 1, 0, 0, 1, 0, 1, 1, 1, 1]"
1,2,39,20.24,121.4624,"[1, 0, 0, 0, 1, 1, 0, 1, 1, 1]"
2,3,39,24.64,68.1104,"[1, 0, 0, 0, 1, 1, 0, 1, 1, 1]"
3,4,39,23.58,80.0436,"[1, 0, 0, 0, 1, 1, 0, 1, 1, 1]"
4,5,38,27.88,31.7456,"[0, 0, 0, 0, 1, 1, 0, 1, 1, 1]"
5,6,45,30.42,43.3636,"[0, 0, 0, 0, 1, 1, 1, 1, 1, 1]"
6,7,40,30.04,71.9184,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
7,8,43,29.98,68.7396,"[1, 0, 0, 1, 1, 1, 0, 1, 1, 1]"
8,9,45,30.96,65.1984,"[1, 0, 0, 1, 0, 1, 1, 1, 1, 1]"
9,10,43,28.32,124.8976,"[1, 0, 0, 1, 1, 1, 0, 1, 1, 1]"
10,11,45,27.68,121.3376,"[1, 0, 0, 1, 0, 1, 1, 1, 1, 1]"
11,12,49,30.50,106.1700,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
12,13,49,34.08,33.7936,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
13,14,49,29.64,161.6304,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
14,15,45,34.68,55.3776,"[1, 0, 0, 1, 0, 1, 1, 1, 1, 1]"
15,16,45,35.38,74.3156,"[0, 0, 1, 1, 1, 1, 0, 1, 1, 1]"
16,17,47,33.68,151.8176,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
17,18,47,35.12,128.7056,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
18,19,47,37.40,54.2000,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
19,20,47,37.08,75.1536,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
20,21,47,37.86,57.4404,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
21,22,47,35.40,161.8000,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
22,23,47,37.96,79.7184,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
23,24,47,37.72,140.6416,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
24,25,47,39.64,79.3104,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
25,26,47,40.72,49.2416,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
26,27,47,39.08,111.5936,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
27,28,47,39.30,115.2500,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
28,29,47,39.52,111.0096,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
29,30,47,39.78,111.0916,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
30,31,47,40.68,78.1776,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
31,32,49,40.54,81.9684,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
32,33,49,41.32,49.9376,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
33,34,49,40.90,48.9300,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
34,35,49,39.82,112.9876,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
35,36,49,40.38,115.4756,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
36,37,49,41.38,81.0356,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
37,38,47,42.76,13.9424,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
38,39,47,43.42,16.5636,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
39,40,47,42.66,17.9044,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
40,41,47,43.12,15.4656,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
41,42,47,43.86,11.0004,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
42,43,47,44.14,9.2404,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
43,44,47,44.38,6.9556,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
44,45,47,43.90,9.8500,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
45,46,47,43.94,9.8964,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
46,47,47,44.16,6.6144,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
47,48,47,43.92,7.6336,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
48,49,47,44.32,6.5776,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
49,50,47,44.80,5.5600,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"

In [21]:
import _pickle as cPickle
with open(r"objects1/5000.pkl", "rb") as input_file:
    e = cPickle.load(input_file)
e.get_history()

    Generation  Best fitness  Mean fitness  Fitness variance      Best genome
0            1            13           6.3             12.81  [1, 0, 1, 1, 1]
1            2            14           7.3             10.21  [0, 1, 1, 1, 1]
2            3            10           4.8              6.76  [1, 1, 1, 1, 0]
3            4            13           6.5             10.85  [1, 0, 1, 1, 1]
4            5            10           5.4              9.44  [1, 1, 1, 1, 0]
5            6            13           7.0              8.20  [1, 0, 1, 1, 1]
6            7            13           7.9              9.89  [1, 0, 1, 1, 1]
7            8            13           6.6              8.04  [1, 0, 1, 1, 1]
8            9            13           6.5              9.45  [1, 0, 1, 1, 1]
9           10            13           6.7             12.21  [1, 0, 1, 1, 1]
10          11             8           4.9              4.29  [1, 0, 1, 1, 0]
11          12             8           4.3              2.81  [1, 0, 1, 1, 0]
12          13             8           4.9              3.89  [1, 0, 1, 1, 0]
13          14             8           4.0              4.00  [1, 0, 1, 1, 0]
14          15             8           4.0              3.20  [1, 0, 1, 1, 0]
15          16             7           3.5              1.45  [0, 0, 1, 1, 0]
16          17             7           3.5              1.45  [0, 0, 1, 1, 0]
17          18             7           3.4              1.44  [0, 0, 1, 1, 0]
18          19             3           3.0              0.00  [0, 0, 1, 0, 0]
19          20             3           3.0              0.00  [0, 0, 1, 0, 0]
20          21             3           3.0              0.00  [0, 0, 1, 0, 0]
21          22             3           3.0              0.00  [0, 0, 1, 0, 0]
22          23             3           3.0              0.00  [0, 0, 1, 0, 0]
23          24             3           3.0              0.00  [0, 0, 1, 0, 0]
24          25             3           3.0              0.00  [0, 0, 1, 0, 0]
25          26             3           3.0              0.00  [0, 0, 1, 0, 0]
26          27             3           3.0              0.00  [0, 0, 1, 0, 0]
27          28             3           3.0              0.00  [0, 0, 1, 0, 0]
28          29             3           3.0              0.00  [0, 0, 1, 0, 0]
29          30             3           3.0              0.00  [0, 0, 1, 0, 0]
30          31             3           3.0              0.00  [0, 0, 1, 0, 0]
31          32             3           3.0              0.00  [0, 0, 1, 0, 0]
32          33             3           3.0              0.00  [0, 0, 1, 0, 0]
33          34             3           3.0              0.00  [0, 0, 1, 0, 0]
34          35             3           3.0              0.00  [0, 0, 1, 0, 0]
35          36             3           3.0              0.00  [0, 0, 1, 0, 0]
36          37             3           3.0              0.00  [0, 0, 1, 0, 0]
37          38             3           3.0              0.00  [0, 0, 1, 0, 0]
38          39             3           3.0              0.00  [0, 0, 1, 0, 0]
39          40             3           3.0              0.00  [0, 0, 1, 0, 0]
40          41             3           3.0              0.00  [0, 0, 1, 0, 0]
41          42             3           3.0              0.00  [0, 0, 1, 0, 0]
42          43             3           3.0              0.00  [0, 0, 1, 0, 0]
43          44             3           3.0              0.00  [0, 0, 1, 0, 0]
44          45             3           3.0              0.00  [0, 0, 1, 0, 0]
45          46             3           3.0              0.00  [0, 0, 1, 0, 0]
46          47             3           3.0              0.00  [0, 0, 1, 0, 0]
47          48             3           3.0              0.00  [0, 0, 1, 0, 0]
48          49             3           3.0              0.00  [0, 0, 1, 0, 0]
49          50             3           3.0              0.00  [0, 0, 1, 0, 0]