In [1]:
from genetic_alg import genetic_alg
from problems import *
from individuals import *

In [18]:
def generate_problems():
    problems = []
    max_total_weights = [10, 20, 30]
    item_counts = [5, 10, 20]
    test_cases = []
    for total_weight in max_total_weights:
        for count in item_counts:
           
            test_case = {
                'maximum_total_weight': total_weight,
                'item_count': count
            }
            test_cases.append(test_case)
            
    for case in test_cases:
        problems.append(knapsack(minimum_item_weight=0,maximum_item_weight=10, **case))
    return problems

In [19]:
problems = generate_problems()
for problem in problems:
    print(problem.get_knapsack_df())

   rewards   weights
0        1  5.116321
1        2  9.663996
2        3  5.041794
3        4  0.506095
4        5  0.171759
   rewards   weights
0        1  4.050226
1        2  4.628962
2        3  6.675277
3        4  9.941655
4        5  5.383287
5        6  0.765346
6        7  6.592301
7        8  9.350103
8        9  1.224573
9       10  1.093633
    rewards   weights
0         1  4.342106
1         2  2.271832
2         3  4.064069
3         4  1.698554
4         5  7.189536
5         6  6.618816
6         7  8.829798
7         8  4.723843
8         9  5.149104
9        10  7.678729
10       11  0.886438
11       12  5.947005
12       13  7.217123
13       14  3.581872
14       15  3.975740
15       16  1.740593
16       17  6.603578
17       18  1.103732
18       19  4.483671
19       20  4.842153
   rewards   weights
0        1  0.454612
1        2  2.371737
2        3  5.114034
3        4  0.768485
4        5  4.872082
   rewards   weights
0        1  4.921560
1        2  4.372768
2        3  0.121007
3        4  3.837183
4        5  9.405323
5        6  0.154164
6        7  2.257070
7        8  9.677482
8        9  5.857863
9       10  4.736275
    rewards   weights
0         1  8.102623
1         2  0.845811
2         3  1.016889
3         4  2.770349
4         5  4.905651
5         6  3.104549
6         7  1.500596
7         8  7.316470
8         9  2.846375
9        10  9.902859
10       11  2.942625
11       12  5.582020
12       13  2.353972
13       14  8.289902
14       15  4.979506
15       16  8.131993
16       17  9.751142
17       18  2.961908
18       19  7.444779
19       20  8.423823
   rewards   weights
0        1  8.147230
1        2  9.958667
2        3  3.160410
3        4  3.250591
4        5  3.937751
   rewards   weights
0        1  9.136132
1        2  8.120717
2        3  8.735666
3        4  6.315329
4        5  4.212772
5        6  2.681723
6        7  2.211576
7        8  7.429583
8        9  7.511583
9       10  9.323814
    rewards   weights
0         1  0.070226
1         2  7.181872
2         3  4.030933
3         4  0.948574
4         5  1.664867
5         6  6.405488
6         7  0.879662
7         8  2.432549
8         9  7.375418
9        10  8.335064
10       11  0.202848
11       12  2.861127
12       13  2.725235
13       14  5.946229
14       15  7.836623
15       16  8.054323
16       17  9.835277
17       18  7.326398
18       19  2.075654
19       20  2.370971

In [20]:
algs = []
for problem in problems:
    alg = genetic_alg(
    pop_size=50,
    genome_size=problem.get_item_count(),
    crossover_type="one point", 
    mutation_method="gene bitflip", 
    mutation_probability=0.1,
    problem=problem,
    genome_type='bitstring',
    selection_method="roulette")
    algs.append(alg)

In [21]:
algs[7].run(50)
algs[7].get_history()

,Generation,Best fitness,Mean fitness,Fitness variance,Best genome
0,1,40,12.76,114.0224,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
1,2,40,19.50,106.8100,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
2,3,40,24.12,91.7056,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
3,4,40,23.56,110.5264,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
4,5,40,24.84,115.1344,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
5,6,40,26.56,92.2064,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
6,7,40,25.56,100.7264,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
7,8,40,26.04,95.9184,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
8,9,40,26.80,103.4400,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
9,10,40,28.92,85.2336,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
10,11,40,28.16,117.3744,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
11,12,40,30.62,69.1556,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
12,13,40,30.44,83.0864,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
13,14,40,32.12,15.5856,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
14,15,40,30.32,56.5376,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
15,16,40,29.08,68.5136,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
16,17,40,31.00,42.7600,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
17,18,40,30.28,59.5216,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
18,19,40,32.24,14.1824,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
19,20,40,31.84,51.1744,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
20,21,40,33.12,9.9456,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
21,22,40,32.60,30.9200,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
22,23,40,33.60,8.4800,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
23,24,40,32.40,48.6400,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
24,25,40,33.96,5.1984,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
25,26,40,34.40,4.4800,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
26,27,40,34.32,4.5376,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
27,28,36,34.16,3.9744,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
28,29,36,34.16,3.9744,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
29,30,36,34.08,3.9936,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
30,31,36,33.84,3.9744,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
31,32,36,33.92,3.9936,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
32,33,36,33.68,3.8976,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
33,34,36,34.24,3.9424,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
34,35,36,34.56,3.6864,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
35,36,36,34.08,3.9936,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
36,37,36,34.00,4.0000,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
37,38,36,34.48,3.7696,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
38,39,36,34.48,3.7696,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
39,40,36,34.40,3.8400,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
40,41,36,34.96,3.0784,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
41,42,36,35.04,2.9184,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
42,43,36,35.12,2.7456,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
43,44,36,35.04,2.9184,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
44,45,36,35.12,2.7456,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
45,46,36,35.12,2.7456,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
46,47,36,35.28,2.3616,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
47,48,36,35.52,1.6896,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
48,49,36,35.60,1.4400,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"
49,50,36,35.68,1.1776,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1]"

In [3]:
alg = genetic_alg(
    pop_size=50,
    genome_size=10,
    crossover_type="one point", 
    mutation_method="gene bitflip", 
    mutation_probability=0.1,
    problem=problem,
    genome_type='bitstring',
    selection_method="roulette")
alg.run(50)

In [17]:
alg = genetic_alg(
    pop_size=50,
    genome_size=10,
    crossover_type="one point", 
    mutation_method="gene bitflip", 
    mutation_probability=0.1,
    problem=problem,
    genome_type='bitstring',
    selection_method="tournament")
alg.run(50)

In [4]:
alg.get_history()

,Generation,Best fitness,Mean fitness,Fitness variance,Best genome
0,1,41,20.80,119.6000,"[0, 1, 0, 0, 1, 0, 1, 1, 1, 1]"
1,2,39,20.24,121.4624,"[1, 0, 0, 0, 1, 1, 0, 1, 1, 1]"
2,3,39,24.64,68.1104,"[1, 0, 0, 0, 1, 1, 0, 1, 1, 1]"
3,4,39,23.58,80.0436,"[1, 0, 0, 0, 1, 1, 0, 1, 1, 1]"
4,5,38,27.88,31.7456,"[0, 0, 0, 0, 1, 1, 0, 1, 1, 1]"
5,6,45,30.42,43.3636,"[0, 0, 0, 0, 1, 1, 1, 1, 1, 1]"
6,7,40,30.04,71.9184,"[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]"
7,8,43,29.98,68.7396,"[1, 0, 0, 1, 1, 1, 0, 1, 1, 1]"
8,9,45,30.96,65.1984,"[1, 0, 0, 1, 0, 1, 1, 1, 1, 1]"
9,10,43,28.32,124.8976,"[1, 0, 0, 1, 1, 1, 0, 1, 1, 1]"
10,11,45,27.68,121.3376,"[1, 0, 0, 1, 0, 1, 1, 1, 1, 1]"
11,12,49,30.50,106.1700,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
12,13,49,34.08,33.7936,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
13,14,49,29.64,161.6304,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
14,15,45,34.68,55.3776,"[1, 0, 0, 1, 0, 1, 1, 1, 1, 1]"
15,16,45,35.38,74.3156,"[0, 0, 1, 1, 1, 1, 0, 1, 1, 1]"
16,17,47,33.68,151.8176,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
17,18,47,35.12,128.7056,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
18,19,47,37.40,54.2000,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
19,20,47,37.08,75.1536,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
20,21,47,37.86,57.4404,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
21,22,47,35.40,161.8000,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
22,23,47,37.96,79.7184,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
23,24,47,37.72,140.6416,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
24,25,47,39.64,79.3104,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
25,26,47,40.72,49.2416,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
26,27,47,39.08,111.5936,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
27,28,47,39.30,115.2500,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
28,29,47,39.52,111.0096,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
29,30,47,39.78,111.0916,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
30,31,47,40.68,78.1776,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
31,32,49,40.54,81.9684,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
32,33,49,41.32,49.9376,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
33,34,49,40.90,48.9300,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
34,35,49,39.82,112.9876,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
35,36,49,40.38,115.4756,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
36,37,49,41.38,81.0356,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1]"
37,38,47,42.76,13.9424,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
38,39,47,43.42,16.5636,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
39,40,47,42.66,17.9044,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
40,41,47,43.12,15.4656,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
41,42,47,43.86,11.0004,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
42,43,47,44.14,9.2404,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
43,44,47,44.38,6.9556,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
44,45,47,43.90,9.8500,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
45,46,47,43.94,9.8964,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
46,47,47,44.16,6.6144,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
47,48,47,43.92,7.6336,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
48,49,47,44.32,6.5776,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"
49,50,47,44.80,5.5600,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1]"